# Simply edit the file path to the wallpaper,
# and set the monitor output to match your setup.
# Use `hyprctl monitors` to get the correct monitor data.
wallpaper {
monitor = eDP-1
path = ~/.config/hypr/wallpapers_bundled/oc_the_blackboard.png
fit_mode = cover
}

splash = false
